---
 working_dir: '.'
 fname_dataset: 'dataset/chembl28-cleaned.smi'
 fname_fps: 'dataset/fps.pkl'
 fname_tokenizer: '.tokenizer.pkl'
 fname_rnn_parameters: 'parameters/rnn.param'
 fname_vae_encoder_parameters: 'parameters/encoder.param'
 fname_vae_decoder_parameters: 'parameters/decoder.param'
 sampled_dir: 'sampled'
 maxLength: 128
 batch_size: 512
 num_epoch: 6
 lr: 5.0e-3

 rnn_param:
  embedding_dim: 32
  hidden_dim: 128
  num_hidden: 3

 vae_param:
  fc_dims: [512, 256, 128]
  latent_dim: 64
  hidden_dim: 128
  num_hidden: 3
